### PR TITLE
Setup scripts to run the clustering pipeline with slurm 

### PR DESCRIPTION
**Pull request by JulioAPeraza**

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
Changes proposed in this pull request:

- Add participant-level `workflow_participant.sbatch` and group-level `workflow_group.sh` code to run the Yeo pipeline on slurm.
- Codes inside `CBIG` are a simplified copy of the Yeo repo, except for `ComputeAverageCorrelationProfile` and `VisualizeCluster`.

Functions to review:
- `workflow_participant.sbatch`
- `workflow_group.sh`
- `ComputeAverageCorrelationProfile.m`
- `VisualizeCluster.m`

-----
Step to run participant-level scripts `workflow_participant.sbatch`:

1. Set workbench dir. You can download it here: 
```
wget https://www.humanconnectome.org/storage/app/media/workbench/workbench-rh_linux64-v1.5.0.zip
```
2. Set CBIG code dir, and BIDS data dir.
3. Create a subject list with the format sub-<>_ses-<> per line
4. Run the script using slurm arrays: 
```
sbatch --array=1-n workflow_participant.sbatch /home/jpera054/Documents/abcd-parcellation/code/abcd_sub_list.txt
```
where `n` is the number of lines/subjects in the subject list `abcd_sub_list.txt`

------
Step to run group-level scripts `workflow_group.sh`:
1. Set CBIG code dir, and BIDS data dir.
```
sbatch workflow_group.sbatch
```

------
**Note:** remember to adapt the slurm variables `#SBATCH`, and `module load <matlab>` to your HPC. The c++ function were compiled on Matlab2020b, but they should work on Matlab2019b (except for the visualization function).

**Comment by JulioAPeraza** [comment]
Next steps:
1. Implement silhouette method for `fs_LR_32k` mesh.

**Comment by JulioAPeraza** [comment]
I added a function to grab the TRs with > 0.2 FD from the concatenated `*motion_mask.mat` files.
Function to review:
- `MotionMask2TXT.m`

That step was added to the participant-level workflow.

**Comment by JessyD** [comment]
@JulioAPeraza 
Is this an intended behaviour? I am running https://github.com/JulioAPeraza/adolescent-brain-parcellation/blob/preprocessing/code/workflow_participant.sbatch. It outputs a file called `2.54797` and the contet's of it are: 
```
$ cat 2.54797
Smoothing 6mm: Sigma -
```

**Comment by JulioAPeraza** [comment]
Thanks for catching that. It was a typo. I just wanted to print the value of sigma on the screen, not to a file.

**Comment by JessyD** [comment]
@JulioAPeraza 
> Note: remember to adapt the slurm variables #SBATCH, and module load <matlab> to your HPC. The c++ function were compiled on Matlab2020b, but they should work on Matlab2019b (except for the visualization function).

Is there a reason why we are using different versions of matlab for different functions? I think it might be easiser to just use one. We could either stick with Matlab2020b or Matlab2019b, we have both installed on the cluster.

**Comment by JulioAPeraza** [comment]
I used Matlab2019b on the script to run a test on the FIU cluster because it is the latest version we have. The c++ functions were compiled on  Matlab2020b because is the one I have on my laptop with the compiler tools. 
It would be great if you could run the script with Matlab2020b.
Thanks!

**Review by JessyD — APPROVED** [review]

**Pull request merged**
